### ISSUE TITLE
Error getting repository data for docker, repository not found

### ISSUE THREAD

**Issue by pdxmaverick** [monitoringartist/zenoss5-core-autodeploy#12]
Having problems installing docker.

I found in line 638 from:
    echo "yum -y -q --enablerepo=docker install docker-engine-${docker_version}"
    yum -y -q --enablerepo=docker install docker-engine-${docker_version}
to:
    echo "yum -y -q --enablerepo=docker-repo install docker-engine-${docker_version}"
    yum -y -q --enablerepo=docker-repo install docker-engine-${docker_version}

**Comment by jangaraj** [comment]
Good point :-) I've fixed it 5 minutes ago.
