### ISSUE TITLE
Install Fails, CentOS

### ISSUE THREAD

**Issue by arrmo** [monitoringartist/zenoss5-core-autodeploy#13]
Hi,

Just an FYI, created a new VM (VMware) with CentOS7 - two issues noted,
- RAM reported as 0 GB (told to continue, mainly cosmetic)
- install fails, serviced noted to fail (below)

Jan 08 16:45:38 zenoss.home systemd[1]: serviced.service: main process exited, code=exited, status=255/n/a
Jan 08 16:45:38 zenoss.home serviced-systemd.sh[61101]: Fri Jan  8 22:45:38 UTC 2016: post-stopping serviced daemon - waiting for serviced to stop
Jan 08 16:45:38 zenoss.home serviced-systemd.sh[61101]: Fri Jan  8 22:45:38 UTC 2016: waiting for serviced daemon to stop
Jan 08 16:45:38 zenoss.home serviced-systemd.sh[61101]: Fri Jan  8 22:45:38 UTC 2016: waiting for serviced to stop listening
Jan 08 16:45:38 zenoss.home serviced-systemd.sh[61101]: Fri Jan  8 22:45:38 UTC 2016: waiting for serviced isvcs to stop
Jan 08 16:45:49 zenoss.home serviced-systemd.sh[61101]: 9d5863cc87a93b754b16006ec7a4651f334d95b766ea0d003cd9d6558c82cde6
Jan 08 16:45:59 zenoss.home serviced-systemd.sh[61101]: f287d89eb4e0be7544226fe6216b0fcaf1254f75f967864d039fec7980024121
Jan 08 16:46:10 zenoss.home serviced-systemd.sh[61101]: e9cc81cfb4be03c6df3f873cf90e918d3832ade1c6591c017789937951e89266
Jan 08 16:46:17 zenoss.home serviced-systemd.sh[61101]: 2dfcc46a28fc69b3b86e1aa3b2f0496df3757a069293a4c187f6ae0ac1b2c913
Jan 08 16:46:18 zenoss.home serviced-systemd.sh[61101]: dcfb3bb536d2f0dc0199c719e56c5244b27ad6e868e8003b4d5f249a6511f511
Jan 08 16:46:28 zenoss.home serviced-systemd.sh[61101]: a3467ccc15590faaaaf0be39f916e7a77110eb7ea64673d589ff1034f44530d2
Jan 08 16:46:28 zenoss.home serviced-systemd.sh[61101]: Fri Jan  8 22:46:28 UTC 2016: serviced is now stopped - done with post-stop
Jan 08 16:46:28 zenoss.home systemd[1]: Unit serviced.service entered failed state.
Jan 08 16:46:28 zenoss.home systemd[1]: serviced.service failed.

Thanks!

**Comment by jangaraj** [comment]
It's your time for manual installation :-)
There is no obvious issue in your log, so I'm closing. Probably it's some docker problem.

**Comment by arrmo** [comment]
NP, will do - just wanted to let you know. Thanks.
